trigger:
 branches:
  include:
    - develop
 paths:
  include:
    - AutomationCatalogForPowerPlatform
variables:
  buildConfiguration: 'Release'
  AppInsightsConnectionString: ''
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
parameters:
  - name: deployResources
    displayName: Deploy Resources
    type: boolean
    default: false
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
      - ${{ if eq(parameters.deployResources, true) }}:
          - stage: DeployResources
            jobs: 
              - job: DeployResourcesJob
                steps:
                  - task: AzureResourceManagerTemplateDeployment@3
                    displayName: "deploy resources"
                    name: deployResources
                    inputs:
                      azureResourceManagerConnection: $(serviceConnection)
                      subscriptionId: $(subscriptionId)
                      resourceGroupName: $(resourceGroupName)
                      catalogPublisherId: $(catalogPublisherId)
                      catalogEnvUrl: $(catalogEnvUrl)
                      location: $(location)
                      action: 'Create Or Update Resource Group'
                      deploymentScope: 'Resource Group'
                      csmFile: AutomationCatalogForPowerPlatform/ACPP.ClientWithCatalog/Infrastructure/template.bicep
                      overrideParameters: '-resourceGroupName "$(resourceGroupName)" -clientId "$(clientId)" -tenantId "$(tenantId)" -appService "$(appService)" -appServicePlan "$(appServicePlan)" -storageAccount "$(storageAccount)" -applicationInsights "$(applicationInsights)" -catalogPublisherId "$(catalogPublisherId)" -catalogEnvUrl "$(catalogEnvUrl)"'
                      deploymentMode: "Incremental"
                      deploymentOutputs: dataDeploymentOutputs
                  - task: PowerShell@2
                    name: SetDeploymentVariables
                    displayName: 'Set deployment variables'
                    inputs:
                      targetType: 'inline'
                      script: |
                        # Get deployment outputs
                        $deploymentOutputs = '$(dataDeploymentOutputs)'
                        Write-Output "Deployment Outputs: $deploymentOutputs"
      - stage: Build
        jobs:      
        - job: API
          steps:
          - task: NuGetAuthenticate@1
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: 'build'
              projects: 'AutomationCatalogForPowerPlatform/ACPP.API/ACPP.API.csproj'
              arguments: '--configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: 'test'
              projects: 'AutomationCatalogForPowerPlatform/ACPP.Tests/ACPP.Tests.csproj'
              arguments: '--configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'AutomationCatalogForPowerPlatform/ACPP.API/ACPP.API.csproj'
              arguments: '--configuration $(buildConfiguration) --output "$(build.artifactstagingdirectory)"'
              zipAfterPublish: false
          templateContext:
            outputs:
            - output: pipelineArtifact
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: dropAPI

        - job: UI
          steps:
          - task: NodeTool@0
            displayName: Install Node
            inputs:
              versionSource: 'spec'
              versionSpec: '18.15.x'
          - task: npmAuthenticate@0
            displayName: Authenticate
            inputs:
              workingFile: 'AutomationCatalogForPowerPlatform/ACPP.ClientWithCatalog/.npmrc'
          - task: Npm@1
            displayName: Install Packages
            inputs:
              command: 'install'
              workingDir: 'AutomationCatalogForPowerPlatform/ACPP.ClientWithCatalog'
          - task: AzureCLI@2
            displayName: Fetch AI Connection String
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                connectionString=$(az monitor app-insights component show --app $(applicationInsights) --resource-group $(resourceGroupName) --query connectionString --output tsv)
                echo "##vso[task.setvariable variable=appInsightsConnectionString]$connectionString"
          - task: CmdLine@2
            displayName: Build
            inputs:
              script: 'SET REACT_APP_BUILD_ID=$(Build.BuildNumber)&&SET REACT_APP_TEAMS_APP_ID=$(teamsAppId)&&SET REACT_APP_CLIENT_ID=$(clientId)&&SET REACT_APP_DEFAULT_TOKEN_SCOPE=api://$(appService).azurewebsites.net/$(clientId)&&SET REACT_APP_ADMIN_ENV=$(adminEnvironment)&&SET REACT_APP_FEEDBACK_FORM_URL=$(feedBackFormUrl)&&SET REACT_APP_FAQ_URL=$(faqUrl)&&SET REACT_APP_AI_CONNECTION_STRING=$(AppInsightsConnectionString)&&npm run build:dev'
              workingDirectory: 'AutomationCatalogForPowerPlatform/ACPP.ClientWithCatalog'
          - task: CmdLine@2
            displayName: Copy locales (temp)
            inputs:
              script: 'xcopy "src\i18n\locales" "build\static\locales\" /e /s /y'
              workingDirectory: 'AutomationCatalogForPowerPlatform/ACPP.ClientWithCatalog'
          - task: CopyFiles@2
            displayName: Copy files
            inputs:
              SourceFolder: 'AutomationCatalogForPowerPlatform/ACPP.ClientWithCatalog/build'
              Contents: |
                **
                !**\*.map
              TargetFolder: '$(Build.ArtifactStagingDirectory)/ACPP.ClientWithCatalog/ClientApp'
          templateContext:
            outputs:
            - output: pipelineArtifact
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: dropUI
      
      - stage: DeployCode
        dependsOn: 
        - Build
        condition: succeeded('Build')
        jobs:
          - deployment: Deploy
            displayName: Deploy
            environment: $(environment)
            strategy:
              runOnce:
                deploy:
                  steps:
                  - task: CmdLine@2
                    displayName: Merge API and UI
                    inputs:
                      script: |
                        xcopy "$(Pipeline.Workspace)\dropAPI\ACPP.API" "$(Build.ArtifactStagingDirectory)\dist\" /e /s 
                        xcopy "$(Pipeline.Workspace)\dropUI\ACPP.ClientWithCatalog\ClientApp" "$(Build.ArtifactStagingDirectory)\dist\ClientApp\" /e /s
                      workingDirectory: '$(Pipeline.Workspace)'
                  - task: AzureRmWebAppDeployment@4
                    displayName: Deploy to Web App
                    inputs:
                      ConnectionType: 'AzureRM'
                      azureSubscription: $(serviceConnection)
                      appType: 'webApp'
                      WebAppName: $(appService)
                      packageForLinux: '$(Build.ArtifactStagingDirectory)/dist'
